apiVersion: v1
kind: Service
metadata:
  name: nats-lb
  namespace: {{ include "nats.namespace" . }}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: nats
  ports:
    - protocol: TCP
      port: 4222
      targetPort: 4222
      name: nats
    - protocol: TCP
      port: 7422
      targetPort: 7422
      name: leafnodes
    - protocol: TCP
      port: 7522
      targetPort: 7522
      name: gateways
    - protocol: TCP
      port: 1883
      targetPort: 1883
      name: mqtt
