version: "3.5"
services:
  nats1:
    container_name: nats1
    image: nats
    ports:
      - "8222:8222" # reporting
      - "4222:4222" # connecting
    volumes:
      - ./cluster/nats1:/data
    networks: ["suu"]
    command: "-DV --name nats1 --server_name nats1 --cluster_name natscluster --http_port 8222 --config /data/nats.conf --routes nats-route://admin:admin@nats1:6222,nats-route://admin:admin@nats2:6222,nats-route://admin:admin@nats3:6222 --jetstream --store_dir /data"  
  nats2:
    container_name: nats2
    image: nats
    ports:
      - "8223:8222" # reporting
      - "4223:4222" # connecting
    volumes:
      - ./cluster/nats2:/data
    networks: ["suu"]
    command: "-DV --name nats2 --server_name nats2 --cluster_name natscluster --http_port 8222 --config /data/nats.conf --routes nats-route://admin:admin@nats1:6222,nats-route://admin:admin@nats2:6222,nats-route://admin:admin@nats3:6222 --jetstream --store_dir /data"
  nats3:
    container_name: nats3
    image: nats
    ports:
      - "8224:8222" # reporting
      - "4224:4222" # connecting
    volumes:
      - ./cluster/nats3:/data
    networks: ["suu"]
    command: "-DV --name nats3 --server_name nats3 --cluster_name natscluster --http_port 8222 --config /data/nats.conf --routes nats-route://admin:admin@nats1:6222,nats-route://admin:admin@nats2:6222,nats-route://admin:admin@nats3:6222 --jetstream --store_dir /data"
  publisher:
    container_name: publisher
    build:
      context: ./publisher
      dockerfile: Dockerfile
    networks: ["suu"]
    image: publisher
  light1:
    container_name: light1
    build:
      context: ./devices/light
      dockerfile: Dockerfile
    networks: ["suu"]
    environment:
      LIGHT_NAME: "Main"
      LIGHT_ROOM: "Kitchen"
    image: light
  light2:
    container_name: light2
    image: light
    networks: ["suu"]
    environment:
      LIGHT_NAME: "Fridge"
      LIGHT_ROOM: "Kitchen"
    
networks:
  suu:
    name: suu
